steps:
  # Step 1: Build the Docker image with PUBLIC config only.
  # NOTE: GEMINI_API_KEY is NOT passed as a build arg.
  # It is set as a Cloud Run runtime secret via Secret Manager.
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - '--no-cache'
      - '-t'
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA
      - '--build-arg'
      - VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY
      - '--build-arg'
      - VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN
      - '--build-arg'
      - VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID
      - '--build-arg'
      - VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET
      - '--build-arg'
      - VITE_FIREBASE_MESSAGING_SENDER_ID=$_VITE_FIREBASE_MESSAGING_SENDER_ID
      - '--build-arg'
      - VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID
      - .

  # Step 2: Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=$_PLATFORM'
      - '--image=$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'

  # Step 4: Install Cloud Functions dependencies & deploy
  - name: node:20
    id: DeployFunctions
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        npm install -g firebase-tools
        cd functions
        if [ -f package-lock.json ]; then npm ci; else npm install; fi
        npm run build
        cd ..
        if ! firebase functions:artifacts:setpolicy --project=$PROJECT_ID --location=us-central1 --days=30 --non-interactive --force; then
          echo "Warning: Unable to set functions artifacts cleanup policy in us-central1; continuing with deploy fallback."
        fi
        max_attempts=3
        attempt=1
        until firebase deploy --only functions --project=$PROJECT_ID --non-interactive --force; do
          if [ "$attempt" -ge "$max_attempts" ]; then
            echo "Functions deploy failed after $attempt attempts."
            exit 1
          fi
          attempt=$((attempt + 1))
          echo "Functions deploy failed; waiting 90s for IAM/Eventarc propagation before retry $attempt/$max_attempts..."
          sleep 90
        done
    waitFor: ['Deploy']

  # Step 5: Deploy Firestore rules
  - name: node:20
    id: DeployRules
    entrypoint: bash
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only firestore:rules --project=$PROJECT_ID --non-interactive
    waitFor: ['Deploy']

images:
  - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
