steps:
  # Step 1: Build the Docker image with all build-time args
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - '--no-cache'
      - '-t'
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA
      - '--build-arg'
      - GEMINI_API_KEY=$_GEMINI_API_KEY
      - '--build-arg'
      - VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY
      - '--build-arg'
      - VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN
      - '--build-arg'
      - VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID
      - '--build-arg'
      - VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET
      - '--build-arg'
      - VITE_FIREBASE_MESSAGING_SENDER_ID=$_VITE_FIREBASE_MESSAGING_SENDER_ID
      - '--build-arg'
      - VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID
      - '--build-arg'
      - VITE_GEMINI_FILE_URI_BASIC=$_VITE_GEMINI_FILE_URI_BASIC
      - '--build-arg'
      - VITE_GEMINI_FILE_URI_DMG=$_VITE_GEMINI_FILE_URI_DMG
      - '--build-arg'
      - VITE_GEMINI_FILE_URI_MM=$_VITE_GEMINI_FILE_URI_MM
      - '--build-arg'
      - VITE_GEMINI_FILE_URI_PHB=$_VITE_GEMINI_FILE_URI_PHB
      - .

  # Step 2: Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=$_PLATFORM'
      - '--image=$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'

images:
  - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
